version: '3'
services:
  primax-store-backend:
    image: primax-store-backend
    container_name: primax-store-backend
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/primaxdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=primaxdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

