### GET request to get all customers
GET http://localhost:8080/api/customers
Accept: application/json

### GET request to get single product
GET http://localhost:8080/api/customers/:id
Accept: application/json



### Send POST request to create
POST http://localhost:8080/api/customers/create
Content-Type: application/json

{
  "firstName": "Brian",
  "lastName": "Holt",
  "email": "brianholt@stripe.com",
  "password": "stripe",
  "gender": "male",
  "phoneNumber": "901-56-5544",
  "address": "Seattle, USA"
}
