### GET request to get all orders
GET http://localhost:8080/api/orders

### GET request to get single order
GET http://localhost:8080/api/orders/:id

### Send POST request to create order with data
POST http://localhost:8080/api/orders/create

{
    "customer": {
        "customerId": "45eb8da7-4f40-4ae4-998b-840d1e8f55f5"
    },
    "products": {
        "productId": "e19c5212-2d3c-4e66-b153-9782899ec8f5"
    }
}


### SEND PUT request to updated the order status by id
PUT http://localhost:8080/api/orders/approve/:id


### Send DELETE request if an order is to be rejected.
DELETE http://localhost:8080/api/orders/reject/:id